# Databricks notebook source
# MAGIC %md
# MAGIC <div style="text-align: center; line-height: 0; padding-top: 9px;">
# MAGIC   <img src="https://learningjournal.github.io/pub-resources/logos/scholarnest_academy.jpg" alt="ScholarNest Academy" style="width: 1400px">
# MAGIC </div>

# COMMAND ----------

# MAGIC %md
# MAGIC ####1. Setup your Environment Variables

# COMMAND ----------

import os

os.environ["OPENAI_API_KEY"]="<Your OpenAI API Key>"
os.environ["LANGCHAIN_TRACING_V2"]="true"
os.environ["LANGCHAIN_API_KEY"]="<Your Langchain API Key>"

# COMMAND ----------

# MAGIC %md 
# MAGIC 1.2 Define a function to show the graph

# COMMAND ----------

def show_app_graph(app):
    import IPython.display as ipd
    try:
        ipd.display(
            ipd.Image(
                app.get_graph().draw_mermaid_png()
                )
            )
    except Exception:
       app.get_graph().print_ascii() 

# COMMAND ----------

# MAGIC %md
# MAGIC #### 2. Create a Graph
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC 2.1 Create a data structure for state that tracks all messages

# COMMAND ----------

from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages

class State(TypedDict):
    #Message list
    messages: Annotated[list, add_messages]

# COMMAND ----------

# MAGIC %md
# MAGIC 2.2 Create a system message for writing an eassay.

# COMMAND ----------

from langchain_core.messages import SystemMessage

essay_prompt = SystemMessage(
    """You are an essay writing assistant who writes excellent 2-paragraph essays.
    Generate the best essay possible for the user's request.
    If the user provides feedback and critique, respond with a revised version of your previous attempts."""
    )

# COMMAND ----------

# MAGIC %md
# MAGIC 2.3 Create a system message to review and feedback an essay.

# COMMAND ----------

feedback_prompt = SystemMessage(
    """You are a teacher grading an essay submission. 
    Generate feedback and recommendations for the user's submission.
    Provide detailed recommendations, including requests for length, depth, style, etc."""
    )

# COMMAND ----------

# MAGIC %md
# MAGIC 2.4 Create an LLM to answer user questions

# COMMAND ----------

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o-mini")

# COMMAND ----------

# MAGIC %md
# MAGIC 2.5 Write a graph node function to answer user questions

# COMMAND ----------

def write_essay(state: State) -> State:
    answer = llm.invoke([essay_prompt] + state["messages"])
    return {"messages": [answer]}

# COMMAND ----------

# MAGIC %md
# MAGIC 2.6 Write a feedback node function. Make sure the essay appears to be generated by human.

# COMMAND ----------

def give_feedback(state: State) -> State:
    from langchain_core.messages import AIMessage, HumanMessage
    cls_map = {AIMessage: HumanMessage, HumanMessage: AIMessage}
    translated = ([feedback_prompt, state["messages"][0]] +
                  [cls_map[msg.__class__](content=msg.content) for msg in state["messages"][1:]])

    feedback = llm.invoke(translated)
    return {"messages": [HumanMessage(content=feedback.content)]}

# COMMAND ----------

# MAGIC %md
# MAGIC 2.7 Wrie a loop condition

# COMMAND ----------

def loop_condition(state: State):
    if len(state["messages"]) > 6:
        return END
    else:
        return "give_feedback"

# COMMAND ----------

# MAGIC %md
# MAGIC 2.8 Create a the graph with nodes and edges

# COMMAND ----------

from langgraph.graph import END, START, StateGraph

builder = StateGraph(State)
builder.add_node("write_essay", write_essay)
builder.add_node("give_feedback", give_feedback)

builder.add_edge(START, "write_essay")
builder.add_conditional_edges("write_essay", loop_condition)
builder.add_edge("give_feedback", "write_essay")

chatbot_app = builder.compile()

# COMMAND ----------

# MAGIC %md
# MAGIC ####3. Execute the graph with tracing

# COMMAND ----------

# MAGIC %md
# MAGIC 3.1 Create a convenient function to chat with the LLM graph

# COMMAND ----------

from langsmith import trace
from langchain_core.messages import HumanMessage

def chat(essay_request):
    with trace(project_name="ReAct Loop",
               inputs={"question": essay_request},
               name="Essay Writing") as rt:
        answer = chatbot_app.invoke({"messages": [HumanMessage(essay_request)]})
        rt.end(outputs={"output": answer})

# COMMAND ----------

# MAGIC %md
# MAGIC 3.2 Setup some messages

# COMMAND ----------

request = "Please write an essay on Apache Spark for Data Engineering"

chat(request)

# COMMAND ----------

# MAGIC %md
# MAGIC &copy; 2021-2025 <a href="https://www.scholarnest.in/">ScholarNest</a>. All rights reserved.<br/>
# MAGIC Apache, Apache Spark, Spark and the Spark logo are trademarks of the <a href="https://www.apache.org/">Apache Software Foundation.</a><br/>
# MAGIC Databricks, Databricks Cloud and the Databricks logo are trademarks of the <a href="https://www.databricks.com/">Databricks Inc.</a><br/>
# MAGIC Hugging Face, Hugging Face Logo, Hugging Face Hub are trademarks of the <a href="https://huggingface.co/"> Hugging Face Inc. </a>
# MAGIC <br/>
# MAGIC <a href="https://www.scholarnest.in/pages/privacy">Privacy Policy</a> | <a href="https://www.scholarnest.in/pages/terms">Terms of Use</a> | <a href="https://www.scholarnest.in/pages/contact">Contact Us</a>